<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\Employee;
use App\Models\JobRole;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        // Helper closure to resolve FK IDs at seed-time
        $branch  = fn (string $code) => Branch::where('code', $code)->value('id');
        $role    = fn (string $code) => JobRole::where('code', $code)->value('id');

        $employees = [
            // ── NAMED: SALES ─────────────────────────────────────────────
            [
                'nrp'           => '6018',
                'full_name'     => 'DADI SUPRIYADI',
                'position_name' => 'Sales Consultant',
                'job_role_id'   => $role('SC001'),
                'branch_id'     => $branch('T154'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2005-03-01',
                'date_of_birth' => '1980-06-15',
                'status'        => 'active',
                'italent_user'  => '6018',
            ],
            [
                'nrp'           => '6027',
                'full_name'     => 'JUNAIDI',
                'position_name' => 'Sales Consultant',
                'job_role_id'   => $role('SC001'),
                'branch_id'     => $branch('T055'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2005-07-01',
                'date_of_birth' => '1981-04-22',
                'status'        => 'active',
                'italent_user'  => '6027',
            ],
            [
                'nrp'           => '10626',
                'full_name'     => 'WILLIAM HARIANTO',
                'position_name' => 'Sales Consultant',
                'job_role_id'   => $role('SC001'),
                'branch_id'     => $branch('T059'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2010-02-14',
                'date_of_birth' => '1985-09-10',
                'status'        => 'active',
                'italent_user'  => '10626',
            ],

            // ── NAMED: AFTERSALES MECHANIC GR T002 ───────────────────────
            [
                'nrp'           => '83567',
                'full_name'     => 'AQSHAL WILDAN',
                'position_name' => 'Mechanic Trainee',
                'job_role_id'   => $role('MTR01'),
                'branch_id'     => $branch('T002'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2024-08-01',
                'date_of_birth' => '2001-03-07',
                'grade'         => 'G4',
                'status'        => 'active',
            ],
            [
                'nrp'           => '84185',
                'full_name'     => 'JEHEZKIEL PRAMARTI',
                'position_name' => 'Mechanic Trainee',
                'job_role_id'   => $role('MTR01'),
                'branch_id'     => $branch('T002'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2024-09-01',
                'date_of_birth' => '2001-11-20',
                'grade'         => 'G4',
                'status'        => 'active',
            ],

            // ── NAMED: AFTERSALES SERVICE HEAD ───────────────────────────
            [
                'nrp'           => '5666',
                'full_name'     => 'SUBAGYO',
                'position_name' => 'Service Head',
                'job_role_id'   => $role('SH001'),
                'branch_id'     => $branch('T009'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '1993-05-01',
                'date_of_birth' => '1968-12-03',
                'grade'         => '4A',
                'status'        => 'active',
                'italent_user'  => '5666',
            ],
            [
                'nrp'           => '5971',
                'full_name'     => 'MUHAMAD MULYADI',
                'position_name' => 'Service Head',
                'job_role_id'   => $role('SH001'),
                'branch_id'     => $branch('T156'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '1995-01-01',
                'date_of_birth' => '1970-07-14',
                'grade'         => '4A',
                'status'        => 'active',
                'italent_user'  => '5971',
            ],
            [
                'nrp'           => '29002',
                'full_name'     => 'KEN ERIC',
                'position_name' => 'Service Head',
                'job_role_id'   => $role('SH001'),
                'branch_id'     => $branch('T012'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2003-03-17',
                'date_of_birth' => '1977-05-30',
                'grade'         => '4B',
                'status'        => 'active',
                'italent_user'  => '29002',
            ],

            // ── NAMED: HC / PD ────────────────────────────────────────────
            [
                'nrp'           => '81485',
                'full_name'     => 'VANESSA ANDINI',
                'position_name' => 'HC Analyst',
                'job_role_id'   => $role('HCA01'),
                'branch_id'     => $branch('T000'),
                'area'          => 'HEAD OFFICE',
                'region'        => 'HEAD OFFICE',
                'employee_type' => 'HO',
                'entry_date'    => '2020-09-01',
                'date_of_birth' => '1997-02-18',
                'hav_score'     => 8,
                'hav_category'  => 'Strong Performers',
                'status'        => 'active',
                'italent_user'  => '81485',
            ],
            [
                'nrp'           => '75773',
                'full_name'     => 'VIOLINA SETIAWAN',
                'position_name' => 'HC Analyst',
                'job_role_id'   => $role('HCA01'),
                'branch_id'     => $branch('T000'),
                'area'          => 'HEAD OFFICE',
                'region'        => 'HEAD OFFICE',
                'employee_type' => 'HO',
                'entry_date'    => '2018-04-02',
                'date_of_birth' => '1994-08-25',
                'hav_score'     => 6,
                'hav_category'  => 'Candidate',
                'status'        => 'active',
                'italent_user'  => '75773',
            ],
            [
                'nrp'           => '80197',
                'full_name'     => 'YEREMIA STEVEN',
                'position_name' => 'Account Supervisor',
                'job_role_id'   => $role('AC001'),
                'branch_id'     => $branch('T700'),
                'area'          => 'KALIMANTAN',
                'region'        => 'JATKALBAL',
                'employee_type' => 'VSP',
                'entry_date'    => '2019-07-15',
                'date_of_birth' => '1993-01-12',
                'hav_score'     => 7,
                'hav_category'  => 'Candidate',
                'status'        => 'active',
                'italent_user'  => '80197',
            ],

            // ── GENERATED: SALES ─────────────────────────────────────────
            [
                'nrp'           => '6098',
                'full_name'     => 'BUDI SANTOSO',
                'position_name' => 'Sales Consultant',
                'job_role_id'   => $role('SC001'),
                'branch_id'     => $branch('T100'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2006-04-10',
                'date_of_birth' => '1982-07-20',
                'status'        => 'active',
            ],
            [
                'nrp'           => '6112',
                'full_name'     => 'AHMAD RIFAI',
                'position_name' => 'Sales Consultant',
                'job_role_id'   => $role('SC001'),
                'branch_id'     => $branch('T102'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2006-10-03',
                'date_of_birth' => '1983-11-08',
                'status'        => 'active',
            ],
            [
                'nrp'           => '6145',
                'full_name'     => 'SITI RAHMAWATI',
                'position_name' => 'Sales Consultant',
                'job_role_id'   => $role('SC001'),
                'branch_id'     => $branch('T105'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2007-01-15',
                'date_of_birth' => '1984-03-29',
                'status'        => 'active',
            ],

            // ── GENERATED: SERVICE ADVISOR ────────────────────────────────
            [
                'nrp'           => '7321',
                'full_name'     => 'DEWI KUSUMA',
                'position_name' => 'Service Advisor',
                'job_role_id'   => $role('SA001'),
                'branch_id'     => $branch('T009'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2009-05-11',
                'date_of_birth' => '1984-12-01',
                'status'        => 'active',
            ],
            [
                'nrp'           => '7456',
                'full_name'     => 'RUDI HERMAWAN',
                'position_name' => 'Service Advisor',
                'job_role_id'   => $role('SA001'),
                'branch_id'     => $branch('T012'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2010-01-07',
                'date_of_birth' => '1985-09-14',
                'status'        => 'active',
            ],
            [
                'nrp'           => '7512',
                'full_name'     => 'NOVI SUSANTI',
                'position_name' => 'Service Advisor',
                'job_role_id'   => $role('SA001'),
                'branch_id'     => $branch('T059'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2010-08-20',
                'date_of_birth' => '1986-04-05',
                'status'        => 'active',
            ],
            [
                'nrp'           => '9456',
                'full_name'     => 'LESTARI WULANDARI',
                'position_name' => 'Service Advisor',
                'job_role_id'   => $role('SA001'),
                'branch_id'     => $branch('T103'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2015-03-22',
                'date_of_birth' => '1990-01-17',
                'status'        => 'active',
            ],

            // ── GENERATED: MECHANIC / FOREMAN ─────────────────────────────
            [
                'nrp'           => '8234',
                'full_name'     => 'AGUS PRIYONO',
                'position_name' => 'Mechanic 1',
                'job_role_id'   => $role('MCH01'),
                'branch_id'     => $branch('T002'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2012-06-01',
                'date_of_birth' => '1990-08-23',
                'grade'         => 'G3',
                'status'        => 'active',
            ],
            [
                'nrp'           => '8567',
                'full_name'     => 'IWAN SETIAWAN',
                'position_name' => 'Mechanic 2',
                'job_role_id'   => $role('MCH02'),
                'branch_id'     => $branch('T009'),
                'area'          => 'DKI1',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2013-02-15',
                'date_of_birth' => '1988-10-11',
                'grade'         => 'G3',
                'status'        => 'active',
            ],
            [
                'nrp'           => '8789',
                'full_name'     => 'DONI PRASETYO',
                'position_name' => 'Foreman',
                'job_role_id'   => $role('FO001'),
                'branch_id'     => $branch('T002'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2008-11-03',
                'date_of_birth' => '1983-05-19',
                'grade'         => 'G2',
                'status'        => 'active',
            ],
            [
                'nrp'           => '66123',
                'full_name'     => 'BAMBANG SUDARSONO',
                'position_name' => 'Foreman',
                'job_role_id'   => $role('FO001'),
                'branch_id'     => $branch('T251'),
                'area'          => 'JABAR',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2007-09-01',
                'date_of_birth' => '1982-02-14',
                'grade'         => 'G2',
                'status'        => 'active',
            ],

            // ── GENERATED: PARTMAN / CRC ──────────────────────────────────
            [
                'nrp'           => '9001',
                'full_name'     => 'FITRI HANDAYANI',
                'position_name' => 'Partman',
                'job_role_id'   => $role('PM001'),
                'branch_id'     => $branch('T100'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2014-07-21',
                'date_of_birth' => '1991-06-09',
                'status'        => 'active',
            ],
            [
                'nrp'           => '9234',
                'full_name'     => 'HENDRA GUNAWAN',
                'position_name' => 'CRC',
                'job_role_id'   => $role('CRC01'),
                'branch_id'     => $branch('T155'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2016-02-08',
                'date_of_birth' => '1993-12-28',
                'status'        => 'active',
            ],

            // ── GENERATED: JABAR / JATIM ──────────────────────────────────
            [
                'nrp'           => '66456',
                'full_name'     => 'SRI WAHYUNI',
                'position_name' => 'Sales Consultant',
                'job_role_id'   => $role('SC001'),
                'branch_id'     => $branch('T252'),
                'area'          => 'JABAR',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2011-05-16',
                'date_of_birth' => '1987-01-30',
                'status'        => 'active',
            ],
            [
                'nrp'           => '66789',
                'full_name'     => 'RINA FITRIANA',
                'position_name' => 'Service Head',
                'job_role_id'   => $role('SH001'),
                'branch_id'     => $branch('T260'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'VSP',
                'entry_date'    => '2006-08-01',
                'date_of_birth' => '1979-07-08',
                'grade'         => '4B',
                'status'        => 'active',
            ],
            [
                'nrp'           => '70001',
                'full_name'     => 'JOKO SUSILO',
                'position_name' => 'Mechanic 3',
                'job_role_id'   => $role('MCH03'),
                'branch_id'     => $branch('T451'),
                'area'          => 'JATIM',
                'region'        => 'JATKALBAL',
                'employee_type' => 'VSP',
                'entry_date'    => '2010-10-11',
                'date_of_birth' => '1986-03-03',
                'grade'         => 'G2',
                'status'        => 'active',
            ],
            [
                'nrp'           => '70234',
                'full_name'     => 'LINDA PRATIWI',
                'position_name' => 'Sales Consultant',
                'job_role_id'   => $role('SC001'),
                'branch_id'     => $branch('T451'),
                'area'          => 'JATIM',
                'region'        => 'JATKALBAL',
                'employee_type' => 'VSP',
                'entry_date'    => '2012-03-05',
                'date_of_birth' => '1988-09-17',
                'status'        => 'active',
            ],

            // ── GENERATED: BP / HC SPECIALIST ─────────────────────────────
            [
                'nrp'           => '82001',
                'full_name'     => 'SYAHRUL RAMADHAN',
                'position_name' => 'Mechanic Trainee BP',
                'job_role_id'   => $role('MTBP1'),
                'branch_id'     => $branch('T004'),
                'area'          => 'DKI2',
                'region'        => 'DKI JABAR PRIME FLEET',
                'employee_type' => 'BP',
                'entry_date'    => '2024-06-01',
                'date_of_birth' => '2001-08-04',
                'status'        => 'active',
            ],
            [
                'nrp'           => '82234',
                'full_name'     => 'NURUL HIDAYAH',
                'position_name' => 'HC Specialist',
                'job_role_id'   => $role('HCS01'),
                'branch_id'     => $branch('T000'),
                'area'          => 'HEAD OFFICE',
                'region'        => 'HEAD OFFICE',
                'employee_type' => 'HO',
                'entry_date'    => '2021-01-04',
                'date_of_birth' => '1995-05-22',
                'hav_score'     => 7,
                'hav_category'  => 'Candidate',
                'status'        => 'active',
                'italent_user'  => '82234',
            ],
        ];

        foreach ($employees as $data) {
            Employee::firstOrCreate(['nrp' => $data['nrp']], $data);
        }

        // Generate 200 more random employees
        $faker = \Faker\Factory::create('id_ID');
        $branches = Branch::all();
        $roles = JobRole::all();
        $areas = ['DKI1', 'DKI2', 'JABAR', 'JATIM', 'SUMATERA', 'KALIMANTAN'];
        $regions = ['DKI JABAR PRIME FLEET', 'JATKALBAL', 'SUMATERA'];

        for ($i = 0; $i < 200; $i++) {
            $branch = $branches->random();
            $role = $roles->random();
            $area = $faker->randomElement($areas);
            $region = $faker->randomElement($regions);

            Employee::create([
                'nrp' => (string)$faker->unique()->numberBetween(100000, 999999),
                'full_name' => $faker->name,
                'position_name' => $role->name,
                'job_role_id' => $role->id,
                'branch_id' => $branch->id,
                'area' => $area,
                'region' => $region,
                'employee_type' => $faker->randomElement(['VSP', 'BP', 'HO']),
                'entry_date' => $faker->date(),
                'date_of_birth' => $faker->date(),
                'status' => 'active',
                'italent_user' => (string)$faker->unique()->numberBetween(100000, 999999),
            ]);
        }
    }
}
